const base=[{name:'어보브반도체',market:'KOSDAQ',avg:12418,qty:1734,price:7780,support:7700,res1:8300,res2:8500,stop:7600,target1:10000,target2:11600,memo:'관망 우선. 7,700원 이탈 시 추가 하락 리스크. 반등 확인 전 물타기 금지.'},{name:'조일알미늄',market:'KOSPI',avg:1580,qty:11233,price:915,support:900,res1:1000,res2:1050,stop:890,target1:1200,target2:1400,memo:'900원 지지 확인 필요. 주식병합 관련 변동성 주의.'}];
let data=JSON.parse(localStorage.getItem('holdings')||'null')||base;
const fmt=n=>Number(n||0).toLocaleString('ko-KR')+'원';
function save(){localStorage.setItem('holdings',JSON.stringify(data));render();}
function resetBase(){if(confirm('기본값으로 복원할까요?')){data=structuredClone(base);save();}}
function go(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.textContent.includes({home:'홈',hold:'보유',check:'체크',ai:'AI',journal:'일지'}[id])))}
function render(){let totalCost=0,totalVal=0;holdings.innerHTML=data.map((s,i)=>{let cost=s.avg*s.qty,val=s.price*s.qty,pnl=val-cost,rate=cost?pnl/cost*100:0;totalCost+=cost;totalVal+=val;let signal=s.price<s.stop?'손절검토':s.price<s.support?'관망':s.price>s.res1?'일부매도 검토':'관망';return `<div class="card holding"><h2>${s.name} <span class="tag">${s.market}</span></h2><h3 class="${pnl>=0?'profit':'loss'}">손익 ${fmt(pnl)} / ${rate.toFixed(2)}%</h3><div class="row"><label>평단<input type="number" value="${s.avg}" onchange="data[${i}].avg=+this.value;save()"></label><label>수량<input type="number" value="${s.qty}" onchange="data[${i}].qty=+this.value;save()"></label><label>현재가<input type="number" value="${s.price}" onchange="data[${i}].price=+this.value;save()"></label><label>지지선<input type="number" value="${s.support}" onchange="data[${i}].support=+this.value;save()"></label><label>1차 저항<input type="number" value="${s.res1}" onchange="data[${i}].res1=+this.value;save()"></label><label>2차 저항<input type="number" value="${s.res2}" onchange="data[${i}].res2=+this.value;save()"></label><label>손절 검토<input type="number" value="${s.stop}" onchange="data[${i}].stop=+this.value;save()"></label><label>1차 매도 구간<input type="number" value="${s.target1}" onchange="data[${i}].target1=+this.value;save()"></label></div><b>AI 신호: ${signal}</b><textarea onchange="data[${i}].memo=this.value;save()">${s.memo}</textarea></div>`}).join('');let pnl=totalVal-totalCost;totalPnl.textContent=fmt(pnl);totalRate.textContent='손익률 '+(totalCost?pnl/totalCost*100:0).toFixed(2)+'%';}
function initChecks(){let items=['미국 증시·나스닥 흐름 확인','환율·미국 10년물·VIX 확인','코스피·코스닥 외국인/기관 수급 확인','프로그램 매매 확인','어보브/조일 시초가·거래량·호가 확인','9:30 전 무리한 매수 금지','추가매수는 지지 확인 후 검토','뉴스·공시 확인'];let saved=JSON.parse(localStorage.getItem('checks')||'{}');checklist.innerHTML=items.map((x,i)=>`<label class="checkitem"><input type="checkbox" ${saved[i]?'checked':''} onchange="savedCheck(${i},this.checked)">${x}</label>`).join('')}
function savedCheck(i,v){let s=JSON.parse(localStorage.getItem('checks')||'{}');s[i]=v;localStorage.setItem('checks',JSON.stringify(s))}
function saveMemo(id){localStorage.setItem(id,document.getElementById(id).value);alert('저장 완료')}
function makeTemplate(){aiMemo.value=`[장 시작 분석]\n1. 해외시장 영향:\n2. 코스피·코스닥 예상:\n3. 외국인·기관·프로그램 수급:\n4. 어보브반도체 중요 가격:\n5. 조일알미늄 중요 가격:\n6. 오늘 대응 전략:\n7. 최악의 시나리오:\n8. 신뢰도:`;saveMemo('aiMemo')}
function saveJournal(){let list=JSON.parse(localStorage.getItem('journal')||'[]');list.unshift({t:jTitle.value,b:jBody.value,d:new Date().toLocaleString()});localStorage.setItem('journal',JSON.stringify(list));jTitle.value='';jBody.value='';renderJournal()}
function renderJournal(){let list=JSON.parse(localStorage.getItem('journal')||'[]');journalList.innerHTML=list.map(x=>`<div class="card"><small>${x.d}</small><h3>${x.t}</h3><p>${x.b}</p></div>`).join('')}
themeBtn.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.theme==='light')document.body.classList.add('light');aiMemo.value=localStorage.aiMemo||'';render();initChecks();renderJournal();go('home');
